### ISSUE TITLE
Add debian specific package_facts dependency

### ISSUE THREAD

**Issue by philnewm** [philnewm/ansible-role-template#3]
The ansible.builtin.package_facts module requires only on debian a dependency.

Just add this task before package_facts gets run

```yaml
- name: Install debian specific package_facts dependency
  become: true
  when: ansible_distribution == "Debian"
  ansible.builtin.package:
    name: python-apt-common
    state: present
```

Maybe tehre's a more convinient solution to this as well.
